---
title: Ernst Fuchs-Sch√∂nbach - Leben und Werk
url: "http://ernst-fuchs.tk"
baseurl: /ernst-fuchs

# Conversion
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

collections:
  compositions:
    output: true
  archives:
    output: true
  photos:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "compositions"
    values:
      layout: compositions
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: archives
  -
    scope:
      path: ""
      type: "photos"
    values:
      layout: photos
---